CREATE TABLE transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    signature VARCHAR(255),
    productCategoryCode VARCHAR(10),
    specVersion VARCHAR(10),
    primaryAccountNumber VARCHAR(20),
    processingCode VARCHAR(10),
    transactionAmount VARCHAR(20),
    transmissionDateTime VARCHAR(20),
    systemTraceAuditNumber VARCHAR(20),
    localTransactionTime VARCHAR(20),
    localTransactionDate VARCHAR(20),
    merchantCategoryCode VARCHAR(10),
    pointOfServiceEntryMode VARCHAR(10),
    acquiringInstitutionIdentifier VARCHAR(20),
    retrievalReferenceNumber VARCHAR(20),
    merchantTerminalId VARCHAR(20),
    merchantIdentifier VARCHAR(20),
    merchantLocation VARCHAR(255),
    transactionCurrencyCode VARCHAR(10),
    productId VARCHAR(20),
    transactionUniqueId VARCHAR(255),
    correlatedTransactionUniqueId VARCHAR(255),
    balanceAmount INTEGER,
    redemptionAccountNumber VARCHAR(100),
    ActivationAccountNumber VARCHAR(100,)
    expiryDate VARCHAR(50),
    status VARCHAR(20)
);
