// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.0--rc1
// source: public-api/repository/grpc/proto/product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListKeyProductServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdProduct  string `protobuf:"bytes,2,opt,name=id_product,json=idProduct,proto3" json:"id_product,omitempty"`
	NumberKeys string `protobuf:"bytes,3,opt,name=number_keys,json=numberKeys,proto3" json:"number_keys,omitempty"`
	Status     string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ListKeyProductServiceRequest) Reset() {
	*x = ListKeyProductServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKeyProductServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeyProductServiceRequest) ProtoMessage() {}

func (x *ListKeyProductServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeyProductServiceRequest.ProtoReflect.Descriptor instead.
func (*ListKeyProductServiceRequest) Descriptor() ([]byte, []int) {
	return file_public_api_repository_grpc_proto_product_proto_rawDescGZIP(), []int{0}
}

func (x *ListKeyProductServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListKeyProductServiceRequest) GetIdProduct() string {
	if x != nil {
		return x.IdProduct
	}
	return ""
}

func (x *ListKeyProductServiceRequest) GetNumberKeys() string {
	if x != nil {
		return x.NumberKeys
	}
	return ""
}

func (x *ListKeyProductServiceRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListKeyProductServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IdProduct  int64  `protobuf:"varint,2,opt,name=id_product,json=idProduct,proto3" json:"id_product,omitempty"`
	NumberKeys string `protobuf:"bytes,3,opt,name=number_keys,json=numberKeys,proto3" json:"number_keys,omitempty"`
	Status     string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ListKeyProductServiceResponse) Reset() {
	*x = ListKeyProductServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKeyProductServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeyProductServiceResponse) ProtoMessage() {}

func (x *ListKeyProductServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeyProductServiceResponse.ProtoReflect.Descriptor instead.
func (*ListKeyProductServiceResponse) Descriptor() ([]byte, []int) {
	return file_public_api_repository_grpc_proto_product_proto_rawDescGZIP(), []int{1}
}

func (x *ListKeyProductServiceResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListKeyProductServiceResponse) GetIdProduct() int64 {
	if x != nil {
		return x.IdProduct
	}
	return 0
}

func (x *ListKeyProductServiceResponse) GetNumberKeys() string {
	if x != nil {
		return x.NumberKeys
	}
	return ""
}

func (x *ListKeyProductServiceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListKeyBulkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*ListKeyProductServiceResponse `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListKeyBulkResponse) Reset() {
	*x = ListKeyBulkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKeyBulkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeyBulkResponse) ProtoMessage() {}

func (x *ListKeyBulkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeyBulkResponse.ProtoReflect.Descriptor instead.
func (*ListKeyBulkResponse) Descriptor() ([]byte, []int) {
	return file_public_api_repository_grpc_proto_product_proto_rawDescGZIP(), []int{2}
}

func (x *ListKeyBulkResponse) GetData() []*ListKeyProductServiceResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateListKeyStatusProductServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListID string `protobuf:"bytes,1,opt,name=ListID,proto3" json:"ListID,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *UpdateListKeyStatusProductServiceRequest) Reset() {
	*x = UpdateListKeyStatusProductServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateListKeyStatusProductServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateListKeyStatusProductServiceRequest) ProtoMessage() {}

func (x *UpdateListKeyStatusProductServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateListKeyStatusProductServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateListKeyStatusProductServiceRequest) Descriptor() ([]byte, []int) {
	return file_public_api_repository_grpc_proto_product_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateListKeyStatusProductServiceRequest) GetListID() string {
	if x != nil {
		return x.ListID
	}
	return ""
}

func (x *UpdateListKeyStatusProductServiceRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateListKeyStatusProductServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *UpdateListKeyStatusProductServiceResponse) Reset() {
	*x = UpdateListKeyStatusProductServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateListKeyStatusProductServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateListKeyStatusProductServiceResponse) ProtoMessage() {}

func (x *UpdateListKeyStatusProductServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateListKeyStatusProductServiceResponse.ProtoReflect.Descriptor instead.
func (*UpdateListKeyStatusProductServiceResponse) Descriptor() ([]byte, []int) {
	return file_public_api_repository_grpc_proto_product_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateListKeyStatusProductServiceResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type ListKeyProductByProductIDAndLimitServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdProduct string `protobuf:"bytes,1,opt,name=id_product,json=idProduct,proto3" json:"id_product,omitempty"`
	Limit     string `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListKeyProductByProductIDAndLimitServiceRequest) Reset() {
	*x = ListKeyProductByProductIDAndLimitServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKeyProductByProductIDAndLimitServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeyProductByProductIDAndLimitServiceRequest) ProtoMessage() {}

func (x *ListKeyProductByProductIDAndLimitServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeyProductByProductIDAndLimitServiceRequest.ProtoReflect.Descriptor instead.
func (*ListKeyProductByProductIDAndLimitServiceRequest) Descriptor() ([]byte, []int) {
	return file_public_api_repository_grpc_proto_product_proto_rawDescGZIP(), []int{5}
}

func (x *ListKeyProductByProductIDAndLimitServiceRequest) GetIdProduct() string {
	if x != nil {
		return x.IdProduct
	}
	return ""
}

func (x *ListKeyProductByProductIDAndLimitServiceRequest) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

type ProductIDRequestServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ProductIDRequestServiceRequest) Reset() {
	*x = ProductIDRequestServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductIDRequestServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductIDRequestServiceRequest) ProtoMessage() {}

func (x *ProductIDRequestServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductIDRequestServiceRequest.ProtoReflect.Descriptor instead.
func (*ProductIDRequestServiceRequest) Descriptor() ([]byte, []int) {
	return file_public_api_repository_grpc_proto_product_proto_rawDescGZIP(), []int{6}
}

func (x *ProductIDRequestServiceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DetailProductServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId   int64  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Sku         string `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
	Tipe        string `protobuf:"bytes,5,opt,name=tipe,proto3" json:"tipe,omitempty"`
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Stok        int64  `protobuf:"varint,7,opt,name=stok,proto3" json:"stok,omitempty"`
	Duration    string `protobuf:"bytes,8,opt,name=duration,proto3" json:"duration,omitempty"`
	Price       string `protobuf:"bytes,9,opt,name=price,proto3" json:"price,omitempty"`
	Discount    string `protobuf:"bytes,10,opt,name=discount,proto3" json:"discount,omitempty"`
	Tax         string `protobuf:"bytes,11,opt,name=tax,proto3" json:"tax,omitempty"`
	FinalPrice  string `protobuf:"bytes,12,opt,name=final_price,json=finalPrice,proto3" json:"final_price,omitempty"`
	DtmCrt      string `protobuf:"bytes,13,opt,name=dtm_crt,json=dtmCrt,proto3" json:"dtm_crt,omitempty"`
	DtmUp       string `protobuf:"bytes,14,opt,name=dtm_up,json=dtmUp,proto3" json:"dtm_up,omitempty"`
}

func (x *DetailProductServiceResponse) Reset() {
	*x = DetailProductServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailProductServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailProductServiceResponse) ProtoMessage() {}

func (x *DetailProductServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailProductServiceResponse.ProtoReflect.Descriptor instead.
func (*DetailProductServiceResponse) Descriptor() ([]byte, []int) {
	return file_public_api_repository_grpc_proto_product_proto_rawDescGZIP(), []int{7}
}

func (x *DetailProductServiceResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DetailProductServiceResponse) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DetailProductServiceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DetailProductServiceResponse) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *DetailProductServiceResponse) GetTipe() string {
	if x != nil {
		return x.Tipe
	}
	return ""
}

func (x *DetailProductServiceResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DetailProductServiceResponse) GetStok() int64 {
	if x != nil {
		return x.Stok
	}
	return 0
}

func (x *DetailProductServiceResponse) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *DetailProductServiceResponse) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *DetailProductServiceResponse) GetDiscount() string {
	if x != nil {
		return x.Discount
	}
	return ""
}

func (x *DetailProductServiceResponse) GetTax() string {
	if x != nil {
		return x.Tax
	}
	return ""
}

func (x *DetailProductServiceResponse) GetFinalPrice() string {
	if x != nil {
		return x.FinalPrice
	}
	return ""
}

func (x *DetailProductServiceResponse) GetDtmCrt() string {
	if x != nil {
		return x.DtmCrt
	}
	return ""
}

func (x *DetailProductServiceResponse) GetDtmUp() string {
	if x != nil {
		return x.DtmUp
	}
	return ""
}

type RequestAdditionalData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page         int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit        int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Id           int32  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Fk_1         int32  `protobuf:"varint,4,opt,name=fk_1,json=fk1,proto3" json:"fk_1,omitempty"`
	Fk_2         string `protobuf:"bytes,5,opt,name=fk_2,json=fk2,proto3" json:"fk_2,omitempty"`
	Fk_3         string `protobuf:"bytes,6,opt,name=fk_3,json=fk3,proto3" json:"fk_3,omitempty"`
	NameSearch   string `protobuf:"bytes,7,opt,name=name_search,json=nameSearch,proto3" json:"name_search,omitempty"`
	Order        string `protobuf:"bytes,8,opt,name=order,proto3" json:"order,omitempty"`
	Sort         string `protobuf:"bytes,9,opt,name=sort,proto3" json:"sort,omitempty"`
	CustomColumn string `protobuf:"bytes,10,opt,name=custom_column,json=customColumn,proto3" json:"custom_column,omitempty"`
}

func (x *RequestAdditionalData) Reset() {
	*x = RequestAdditionalData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestAdditionalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAdditionalData) ProtoMessage() {}

func (x *RequestAdditionalData) ProtoReflect() protoreflect.Message {
	mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAdditionalData.ProtoReflect.Descriptor instead.
func (*RequestAdditionalData) Descriptor() ([]byte, []int) {
	return file_public_api_repository_grpc_proto_product_proto_rawDescGZIP(), []int{8}
}

func (x *RequestAdditionalData) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RequestAdditionalData) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RequestAdditionalData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RequestAdditionalData) GetFk_1() int32 {
	if x != nil {
		return x.Fk_1
	}
	return 0
}

func (x *RequestAdditionalData) GetFk_2() string {
	if x != nil {
		return x.Fk_2
	}
	return ""
}

func (x *RequestAdditionalData) GetFk_3() string {
	if x != nil {
		return x.Fk_3
	}
	return ""
}

func (x *RequestAdditionalData) GetNameSearch() string {
	if x != nil {
		return x.NameSearch
	}
	return ""
}

func (x *RequestAdditionalData) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *RequestAdditionalData) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *RequestAdditionalData) GetCustomColumn() string {
	if x != nil {
		return x.CustomColumn
	}
	return ""
}

type MetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalData uint32 `protobuf:"varint,1,opt,name=total_data,json=totalData,proto3" json:"total_data,omitempty"`
	TotalPage uint32 `protobuf:"varint,2,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	Page      uint32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit     uint32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Sort      string `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Order     string `protobuf:"bytes,6,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *MetaData) Reset() {
	*x = MetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData) ProtoMessage() {}

func (x *MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData.ProtoReflect.Descriptor instead.
func (*MetaData) Descriptor() ([]byte, []int) {
	return file_public_api_repository_grpc_proto_product_proto_rawDescGZIP(), []int{9}
}

func (x *MetaData) GetTotalData() uint32 {
	if x != nil {
		return x.TotalData
	}
	return 0
}

func (x *MetaData) GetTotalPage() uint32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *MetaData) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *MetaData) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *MetaData) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *MetaData) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type ProductDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Stok       int32   `protobuf:"varint,2,opt,name=stok,proto3" json:"stok,omitempty"`
	Duration   string  `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Price      float64 `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Tax        int32   `protobuf:"varint,5,opt,name=tax,proto3" json:"tax,omitempty"`
	FinalPrice float64 `protobuf:"fixed64,6,opt,name=final_price,json=finalPrice,proto3" json:"final_price,omitempty"`
	// 'discount' is marked as optional because it is a pointer in Go
	Discount int32 `protobuf:"varint,7,opt,name=discount,proto3" json:"discount,omitempty"`
}

func (x *ProductDetail) Reset() {
	*x = ProductDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDetail) ProtoMessage() {}

func (x *ProductDetail) ProtoReflect() protoreflect.Message {
	mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDetail.ProtoReflect.Descriptor instead.
func (*ProductDetail) Descriptor() ([]byte, []int) {
	return file_public_api_repository_grpc_proto_product_proto_rawDescGZIP(), []int{10}
}

func (x *ProductDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductDetail) GetStok() int32 {
	if x != nil {
		return x.Stok
	}
	return 0
}

func (x *ProductDetail) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *ProductDetail) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductDetail) GetTax() int32 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *ProductDetail) GetFinalPrice() float64 {
	if x != nil {
		return x.FinalPrice
	}
	return 0
}

func (x *ProductDetail) GetDiscount() int32 {
	if x != nil {
		return x.Discount
	}
	return 0
}

type ProductResponseDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sku           string           `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Tipe          string           `protobuf:"bytes,4,opt,name=tipe,proto3" json:"tipe,omitempty"`
	Desc          string           `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	DetailProduct []*ProductDetail `protobuf:"bytes,6,rep,name=detail_product,json=detailProduct,proto3" json:"detail_product,omitempty"`
	DtmCrt        string           `protobuf:"bytes,7,opt,name=dtm_crt,proto3" json:"dtm_crt,omitempty"`
	DtmUpd        string           `protobuf:"bytes,8,opt,name=dtm_upd,json=dtmUpd,proto3" json:"dtm_upd,omitempty"`
}

func (x *ProductResponseDTO) Reset() {
	*x = ProductResponseDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductResponseDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponseDTO) ProtoMessage() {}

func (x *ProductResponseDTO) ProtoReflect() protoreflect.Message {
	mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponseDTO.ProtoReflect.Descriptor instead.
func (*ProductResponseDTO) Descriptor() ([]byte, []int) {
	return file_public_api_repository_grpc_proto_product_proto_rawDescGZIP(), []int{11}
}

func (x *ProductResponseDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductResponseDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductResponseDTO) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ProductResponseDTO) GetTipe() string {
	if x != nil {
		return x.Tipe
	}
	return ""
}

func (x *ProductResponseDTO) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ProductResponseDTO) GetDetailProduct() []*ProductDetail {
	if x != nil {
		return x.DetailProduct
	}
	return nil
}

func (x *ProductResponseDTO) GetDtmCrt() string {
	if x != nil {
		return x.DtmCrt
	}
	return ""
}

func (x *ProductResponseDTO) GetDtmUpd() string {
	if x != nil {
		return x.DtmUpd
	}
	return ""
}

type GetAllProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetaData *MetaData             `protobuf:"bytes,1,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	Data     []*ProductResponseDTO `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAllProductResponse) Reset() {
	*x = GetAllProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProductResponse) ProtoMessage() {}

func (x *GetAllProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_api_repository_grpc_proto_product_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProductResponse.ProtoReflect.Descriptor instead.
func (*GetAllProductResponse) Descriptor() ([]byte, []int) {
	return file_public_api_repository_grpc_proto_product_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllProductResponse) GetMetaData() *MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *GetAllProductResponse) GetData() []*ProductResponseDTO {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_public_api_repository_grpc_proto_product_proto protoreflect.FileDescriptor

var file_public_api_repository_grpc_proto_product_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x22, 0x86, 0x01, 0x0a, 0x1c, 0x4c, 0x69,
	0x73, 0x74, 0x4b, 0x65, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x64,
	0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x69, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x87, 0x01, 0x0a, 0x1d, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x69, 0x64, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6b, 0x65,
	0x79, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x4b, 0x65, 0x79, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x51, 0x0a, 0x13,
	0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x42, 0x75, 0x6c, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x4b, 0x65, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x5a, 0x0a, 0x28, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4c,
	0x69, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4c, 0x69, 0x73,
	0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x47, 0x0a, 0x29, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x66, 0x0a, 0x2f, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49,
	0x44, 0x41, 0x6e, 0x64, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x64, 0x5f, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x64, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x30, 0x0a, 0x1e,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xee,
	0x02, 0x0a, 0x1c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x73, 0x6b, 0x75, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74,
	0x6f, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x6b, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x61, 0x78, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x78, 0x12, 0x1f,
	0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x64, 0x74, 0x6d, 0x5f, 0x63, 0x72, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x64, 0x74, 0x6d, 0x43, 0x72, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x74, 0x6d, 0x5f,
	0x75, 0x70, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x74, 0x6d, 0x55, 0x70, 0x22,
	0xfa, 0x01, 0x0a, 0x15, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x64, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x11, 0x0a, 0x04, 0x66, 0x6b, 0x5f, 0x31, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x66, 0x6b, 0x31, 0x12, 0x11, 0x0a, 0x04, 0x66, 0x6b, 0x5f, 0x32, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x6b, 0x32, 0x12, 0x11, 0x0a, 0x04, 0x66, 0x6b, 0x5f,
	0x33, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x6b, 0x33, 0x12, 0x1f, 0x0a, 0x0b,
	0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x14, 0x0a,
	0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22, 0x9c, 0x01, 0x0a,
	0x08, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0xb4, 0x01, 0x0a, 0x0d,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x74, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x74, 0x6f,
	0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x74, 0x61, 0x78, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x66, 0x69, 0x6e, 0x61,
	0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0xe4, 0x01, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x54, 0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x6b, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x69, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x3d, 0x0a, 0x0e, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0d, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x74, 0x6d, 0x5f, 0x63, 0x72,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x74, 0x6d, 0x5f, 0x63, 0x72, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x64, 0x74, 0x6d, 0x5f, 0x75, 0x70, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x74, 0x6d, 0x55, 0x70, 0x64, 0x22, 0x78, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x2f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x54, 0x4f, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x32, 0xac, 0x04, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x4b, 0x65, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x25, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x4b, 0x65, 0x79, 0x42, 0x75, 0x6c, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x85, 0x01, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x4b, 0x65, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x12, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x80, 0x01, 0x0a, 0x24, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x42, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x41, 0x6e, 0x64, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x38, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x4b, 0x65, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x42, 0x79, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x41, 0x6e, 0x64, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x42,
	0x75, 0x6c, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x62, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x42, 0x79, 0x49, 0x44, 0x12,
	0x27, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x44, 0x61,
	0x74, 0x61, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_public_api_repository_grpc_proto_product_proto_rawDescOnce sync.Once
	file_public_api_repository_grpc_proto_product_proto_rawDescData = file_public_api_repository_grpc_proto_product_proto_rawDesc
)

func file_public_api_repository_grpc_proto_product_proto_rawDescGZIP() []byte {
	file_public_api_repository_grpc_proto_product_proto_rawDescOnce.Do(func() {
		file_public_api_repository_grpc_proto_product_proto_rawDescData = protoimpl.X.CompressGZIP(file_public_api_repository_grpc_proto_product_proto_rawDescData)
	})
	return file_public_api_repository_grpc_proto_product_proto_rawDescData
}

var file_public_api_repository_grpc_proto_product_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_public_api_repository_grpc_proto_product_proto_goTypes = []interface{}{
	(*ListKeyProductServiceRequest)(nil),                    // 0: product.ListKeyProductServiceRequest
	(*ListKeyProductServiceResponse)(nil),                   // 1: product.ListKeyProductServiceResponse
	(*ListKeyBulkResponse)(nil),                             // 2: product.ListKeyBulkResponse
	(*UpdateListKeyStatusProductServiceRequest)(nil),        // 3: product.UpdateListKeyStatusProductServiceRequest
	(*UpdateListKeyStatusProductServiceResponse)(nil),       // 4: product.UpdateListKeyStatusProductServiceResponse
	(*ListKeyProductByProductIDAndLimitServiceRequest)(nil), // 5: product.ListKeyProductByProductIDAndLimitServiceRequest
	(*ProductIDRequestServiceRequest)(nil),                  // 6: product.ProductIDRequestServiceRequest
	(*DetailProductServiceResponse)(nil),                    // 7: product.DetailProductServiceResponse
	(*RequestAdditionalData)(nil),                           // 8: product.RequestAdditionalData
	(*MetaData)(nil),                                        // 9: product.MetaData
	(*ProductDetail)(nil),                                   // 10: product.ProductDetail
	(*ProductResponseDTO)(nil),                              // 11: product.ProductResponseDTO
	(*GetAllProductResponse)(nil),                           // 12: product.GetAllProductResponse
}
var file_public_api_repository_grpc_proto_product_proto_depIdxs = []int32{
	1,  // 0: product.ListKeyBulkResponse.data:type_name -> product.ListKeyProductServiceResponse
	10, // 1: product.ProductResponseDTO.detail_product:type_name -> product.ProductDetail
	9,  // 2: product.GetAllProductResponse.meta_data:type_name -> product.MetaData
	11, // 3: product.GetAllProductResponse.data:type_name -> product.ProductResponseDTO
	0,  // 4: product.ProductService.GetListKeyProduct:input_type -> product.ListKeyProductServiceRequest
	3,  // 5: product.ProductService.UpdateListKeyStatusProduct:input_type -> product.UpdateListKeyStatusProductServiceRequest
	5,  // 6: product.ProductService.GetListKeyProductByProductIDAndLimit:input_type -> product.ListKeyProductByProductIDAndLimitServiceRequest
	6,  // 7: product.ProductService.GetProductByID:input_type -> product.ProductIDRequestServiceRequest
	8,  // 8: product.ProductService.GetAllProduct:input_type -> product.RequestAdditionalData
	2,  // 9: product.ProductService.GetListKeyProduct:output_type -> product.ListKeyBulkResponse
	4,  // 10: product.ProductService.UpdateListKeyStatusProduct:output_type -> product.UpdateListKeyStatusProductServiceResponse
	2,  // 11: product.ProductService.GetListKeyProductByProductIDAndLimit:output_type -> product.ListKeyBulkResponse
	7,  // 12: product.ProductService.GetProductByID:output_type -> product.DetailProductServiceResponse
	12, // 13: product.ProductService.GetAllProduct:output_type -> product.GetAllProductResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_public_api_repository_grpc_proto_product_proto_init() }
func file_public_api_repository_grpc_proto_product_proto_init() {
	if File_public_api_repository_grpc_proto_product_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_public_api_repository_grpc_proto_product_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListKeyProductServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_api_repository_grpc_proto_product_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListKeyProductServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_api_repository_grpc_proto_product_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListKeyBulkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_api_repository_grpc_proto_product_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateListKeyStatusProductServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_api_repository_grpc_proto_product_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateListKeyStatusProductServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_api_repository_grpc_proto_product_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListKeyProductByProductIDAndLimitServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_api_repository_grpc_proto_product_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductIDRequestServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_api_repository_grpc_proto_product_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetailProductServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_api_repository_grpc_proto_product_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestAdditionalData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_api_repository_grpc_proto_product_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_api_repository_grpc_proto_product_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_api_repository_grpc_proto_product_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductResponseDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_api_repository_grpc_proto_product_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_public_api_repository_grpc_proto_product_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_public_api_repository_grpc_proto_product_proto_goTypes,
		DependencyIndexes: file_public_api_repository_grpc_proto_product_proto_depIdxs,
		MessageInfos:      file_public_api_repository_grpc_proto_product_proto_msgTypes,
	}.Build()
	File_public_api_repository_grpc_proto_product_proto = out.File
	file_public_api_repository_grpc_proto_product_proto_rawDesc = nil
	file_public_api_repository_grpc_proto_product_proto_goTypes = nil
	file_public_api_repository_grpc_proto_product_proto_depIdxs = nil
}
